### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by ArturKontrabaev** [MStankiewiczOfficial/Hi-Notch#1]
### Describe the solution you'd like

Hi, really like what you did, want to add/customize a little

**Music playback**
I'd like to see what is playing always when it does is it possible to 
1. always show track name when it is playing ?
2. when it is paused show button play (like pause when playing) and also next and prev track ?

**Battery**
Currently I'm using Aldente app for charching and controlling battery, is it possible to use it menu icon instead of the one you do and also add rule that is appears when battery is 20% or less (currently I use bartender for this scenario)

**Display and my own buttons**
Can I actually customise it myself ? for example I have couple of menus for display switch and audiooutput created in bettertouchtool, I'd love to add them also to dropdown menu?
I can send examples if required

Thanks in advance

### Statements

- [X] I verified that the suggestion has not already been requested on GitHub.
- [X] I verified that the suggestion has not already been requested on BTT Forum.

**Comment by stankiewiczmichal** [comment]
Hi, thank you for your issue. I'm happy to answer your questions.

**Music playback**
Due to technical limitations, I am unable to implement this in the main version of Hi Notch!, while I already have plans to add it as an add-on that will be installed separately.

**Battery**
I also use the AlDente app, but so far I have not been able to find a way to integrate it with BetterTouchTool. I have not found information in the documentation about the ability to control and retrieve information using AppleScript, JavaScript or shell scripts in this software, but I will send an email to its developers to ask about this.

**Display and my own buttons**
Of course you can do this, but keep in mind that you will lose your changes once you upgrade Hi Notch! to a newer version. All you have to do is open the BTT configuration, then under the "Custom Floating Menus & Desktop Widgets" category change the settings for the corresponding menu. If you need more information, then let me know. Just be warned that I am not responsible for any errors that modifying Hi Notch! may cause.

**Comment by ArturKontrabaev** [comment]
**Music**
the most important part for me ) I listen all the time 
my current solution is working with help of app  called Yandex.music - it's unofficial app for music cloud service that works in russia, it has separate menu app looking like this when it's off
<img width="403" alt="image" src="https://github.com/MStankiewiczOfficial/Hi-Notch/assets/60569907/a075410c-42d3-4211-8ec1-05cf8a46a77a">

and when you turn it on it shows song currently playing
so it's almost the same but with playback buttons if you press on the song
<img width="301" alt="image" src="https://github.com/MStankiewiczOfficial/Hi-Notch/assets/60569907/7e54f3f1-eb50-46d1-a368-d69b41e2c91f">

what I like in you solution is that it looks more stylish, functionality on currently used is fine btw.
so if it is hard to implement playback buttons I will go on with this one )

**Battery**
I wonder how they do it with bartender, seems like this is the thing we need to understand.
and if we do we can customise menu as we wish to )
maybe we can write asking devs ?

**Comment by ArturKontrabaev** [comment]
btw can you explain how play button appears ? maybe I will be able to customise myself, where should I dig into ?

**Comment by ArturKontrabaev** [comment]
when I start playing music pause button appears on hinotch, when I press pause all dissaperas and button search and copy appear
so it' seems like not much to be done, just make 2 buttons and don't let them dissapear from screen

**Comment by ArturKontrabaev** [comment]
decided to summarise my vision

1. play/pause button is always shown
2. when playback starts 
 - string with song title is shown and pinned
 - next prev buttons appear
4. double click or click on song title hides it but buttons still visible

**Comment by ArturKontrabaev** [comment]
today found out that it is not shown on external display ((( can you add it as well ?

**Comment by ArturKontrabaev** [comment]
and when I zoom buttons don't work (

**Comment by stankiewiczmichal** [comment]
Regarding the play button - it is set to display only when the media is playing, so that it does not display all the time. It's not ideal, but I haven't found a better solution that doesn't interfere with the use of the other Statuses. I will see what else I can do in this regard.
![image](https://github.com/MStankiewiczOfficial/Hi-Notch/assets/42030591/a98ab7f2-0dc9-4e17-bf84-11f6f3fabee5)

Regarding the second display - there are no plans to introduce such a feature, due to the fact that Hi Notch! is an extension of Notch, yet external screens do not have it.
